# Generated by Django 5.0.13 on 2025-03-10 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[(1, 'General knowledge'), (2, 'IT knowledge')], max_length=20)),
                ('created_date', models.DateField()),
                ('image1', models.FileField(blank=True, null=True, upload_to='news_images/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='news_images/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='news_images/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='news_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
